name: Build, Test, and Publish to NuGet

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore

      - name: Publish NuGet package
        if:  github.ref == 'refs/heads/main' && success()
        run: dotnet pack Turbine/Turbine.csproj --configuration Release --no-build --output out

      - name: Push to NuGet
        if:  github.ref == 'refs/heads/main' && success()
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Turbine/Turbine.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
